### ISSUE TITLE
How do you exit i-search and set a mark?

### ISSUE THREAD

**Issue by posguy99** [paaguti/mg3a#5]
Big emacs and mg2 both accept `RET` to exit the search and set a mark.

But mg3a doesn't.  Instead, it adds a newline to the search string.

![2022-06-03-16-16-41 image](https://user-images.githubusercontent.com/408644/171965878-f87d61ad-71fb-43c2-925e-9c17b286ed13.jpg)

![2022-06-03-16-17-05 image](https://user-images.githubusercontent.com/408644/171965892-f90b10f9-31bc-4967-812c-2ddeec680d1d.jpg)

What am I missing?

**Comment by posguy99** [comment]
NVM, I found my own answer by reading `search.c`, you use `ESC`.

mg2 accepts `ESC` here as well, big emacs does not, it starts an ESC- prefix.

**Comment by paaguti** [comment]
Yup, this comes from mg2
PA

Enviado desde mi iPhone

**Comment by posguy99** [comment]
Both big emacs and mg2 accept RET there to set the mark.

-- 
Marc Wilson
***@***.***

**Comment by paaguti** [comment]
Will see what I can do once the end-of-semester peak is over. To many essays to read :)

Enviado desde mi iPhone
